stages:
  - pre-build
  - build

list-tags:
  stage: pre-build
  image: everpeace/curl-jq
  variables:
    BASE_TAGS_API_URL: https://hub.docker.com/v2/repositories/drupaldocker/php/tags/?page_size=9999
    BASE_TAGS_FILTER: apache
  script:
    - curl --insecure --silent $BASE_TAGS_API_URL | jq '."results"[]["name"]' --raw-output | grep $BASE_TAGS_FILTER > tags_list.txt
  artifacts:
    untracked: true

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cat tags_list.txt
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - |
      while read tag; do
        docker build --pull -t "$CI_REGISTRY_IMAGE:$tag" --build-arg "BASE_IMAGE_TAG=$tag" .
        docker push "$CI_REGISTRY_IMAGE:$tag"
      done < tags_list.txt
  only:
    - master
    - autotags
